convoy-instance:
    restart: always
    labels:
        io.rancher.container.pull_image: always
    entrypoint:
        - /bin/bash
        - -c
    command:
        - /usr/local/bin/convoy-start --mnt-ns /host/proc/1/ns/mnt \
            --drivers longhorn \
            --driver-opts lh.rancherurl=http://104.197.100.82:8080/ \
            --driver-opts lh.rancheraccesskey=E7182AB3ECC98B71D954 \
            --driver-opts lh.ranchersecretkey=gCSZmRm1D5W3LBMAmv9veZKGk67haE8bPuG4eKqP
    privileged: true
    working_dir: /storage
    volumes:
        - /dev:/host/dev
        - /proc:/host/proc
        - /var/lib/convoy:/var/lib/convoy
        - /storage
    image: yasker/convoy:test
